name: kino-slow

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch: {} # manual run button

permissions:
  contents: read

concurrency:
  group: kino-screenshots
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: install deps
        run: npm ci

      # optional: puppeteer likes these flags in ci; if you already add them in code, remove this step
      - name: write ci env
        run: |
          echo "PUPPETEER_SKIP_DOWNLOAD=" >> $GITHUB_ENV

      - name: run coordinator
        env:
          # put any secrets you need here later (api keys, etc)
          # R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          # R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          # R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          # R2_BUCKET: ${{ secrets.R2_BUCKET }}
          NODE_ENV: production
        run: |
          node scripts/kino.js g x fit lit biz adv

      - name: upload screenshots artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ github.run_number }}
          path: |
            puppeteer/screenshots/**/*
          if-no-files-found: ignore
          retention-days: 7
