name: kino-fast

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch: {} # manual run button

permissions:
  contents: read

concurrency:
  group: kino-screenshots-fast
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      # install system chrome for puppeteer
      - name: setup chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: run coordinator
        env:
          NODE_ENV: production
          # pass the chrome binary path to puppeteer
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}
        run: |
          node scripts/kino.js v tv

      - name: upload screenshots artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-fast-${{ github.run_number }}
          path: |
            puppeteer/screenshots/**/*
          if-no-files-found: ignore
          retention-days: 7
